# Pytorch 
[*PyTorch*](https://www.geeksforgeeks.org/deep-learning/getting-started-with-pytorch/) is a Python-based deep learning library that runs on CPU by default and supports GPU acceleration using CUDA. It follows a define-by-run approach, creating dynamic computation graphs during execution, which makes debugging and customization easier.

[*PyTorch*](https://github.com/pytorch/pytorch) is a Python package that provides two high-level features:
* Tensor computation (like NumPy) with strong GPU acceleration
* Deep neural networks built on a tape-based autograd system

## INSTALLATION

For efficient processing and stability, correct version of PyTorch must be installed based on the computer's hardware (NVIDIA, AMD, Apple Silicon, or Intel). 

---

### 1: Finding CUDA version
Before running any installation commands, we need to find the CUDA version

| Hardware Brand | System Check Command | PyTorch Backend Device Name |
| :--- | :--- | :--- |
| **NVIDIA GPU** | Run `nvidia-smi` in terminal | `cuda` |
| **AMD GPU** (Linux/Windows) | Run `rocm-smi` in terminal | `cuda` (via HIP translation layer) |
| **Apple Silicon** (M1/M2/M3/M4) | Check **About This Mac** | `mps` (Metal Performance Shaders) |
| **No Dedicated GPU** | N/A | `cpu` |

---

### Step 2: Selecting PyTorch Version
Based on the OS, CUDA version, GPU we should find a proper Pytorch version for the device we are using. Pytorch has an official website which will give the required bash command for installing the library based on your device.

1. First visit [PyTorch](https://pytorch.org/get-started/locally/).
2. Scroll below and pick appropriate environment settings:
   * **OS:** Windows, Linux, or macOS.
   * **Package:** Pip or Conda.
   * **Compute Platform:** Select **CUDA** (for NVIDIA), **ROCm** (for AMD), **MPS/Default** (for Apple Silicon), or **CPU**.

---

### Step 3: Run the Installation Command
Copy the tailored command from the site and run it in bash.

### Example:

#### CUDA Version (Nvidia)

```bash
nvidia-smi

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   58C    P8             12W /   85W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

#### For NVIDIA (CUDA 12.1):
```bash
pip3 install torch torchvision torchaudio --index-url [https://download.pytorch.org/whl/cu121](https://download.pytorch.org/whl/cu121)
```

For stability, CUDA 12.1 was chosed despite the command `nvidia-smi` which shows CUDA Version: 13.1 on the top right of the output.

## Importing Pytorch
After Installation we may start by importing the dependencies (Pytorch) and checking the version.

In [603]:
import torch 
torch.__version__

'2.12.0+cu126'

## Core Data Structures in Pytorch 
Pytorch uses Tensors as the core data scructure. Tensors are a type of multi-dimensional data structure that behave just like matrices or arrays. They are comparable to arrays from NumPy. 

### Why are Tensors important?
The distinguishing feature between NumPy arrays and Tensors is that Tensors can be processed parallelly using a GPU or other hardware accelerators. This makes Tensors extremely efficient at processing data, and so Tensors are an ovious choice for Machine Learning.

Furthermore, Tensors support Autograd which is a Pytorch feature that allows automatic calculation of gradients which are needed to update model parameters for backpropagation.

## What is Tensor Rank?
[Tensor rank](https://www.geeksforgeeks.org/deep-learning/what-is-tensor-and-tensor-shapes/), also known as the tensor's number of dimensions, is a fundamental concept in TensorFlow. It indicates the number of dimensions present in a tensor.

Here's a brief overview of tensor rank:

Rank 0: Scalars. Tensors of rank 0 represent single values.
Rank 1: Vectors. Tensors of rank 1 have one dimension and represent arrays of values.
Rank 2: Matrices. Tensors of rank 2 have two dimensions and represent 2D arrays of values.
Rank 3 and above: Tensors of rank 3 or higher have three or more dimensions and represent higher-dimensional arrays of values.

## Types of Tensors
Tensors can be classified into three types based on the order.
* Scalar [0-order]
* Vector [1-order]
* Matrix [2-order]
* Tensor [n-order]

</br>

<p align="center">
  <img src="./Images/Tensor-types.jpg" alt="Tensor Types" />
  <br>
  <em align= "center">Types of Tensors</em>
</p>


### Scalar
A scalar is 0-order, 0-rank, and dimensionless (i.e shapeless and has no axis). The core physical and mathematical point is that it has no direction, so it can be interpreted just a single magnitude.

In [604]:
# creating scalar using tensor
scalar = torch.tensor(7)

In [605]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


### Vector
Vector is first order and first rank. Its also has a dimension along an axis.
In programming we can think of a vector as a 1-dimensional array. Each number in the array represents the vector's magnitude along a specific coordinate axis (like $x, y, z$).

In [606]:
# vector
vector = torch.tensor([7, 8, 9, 10])

In [607]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


### Matrix
A matrix is a second rank and second order tensor. Its represented by two directions/axes ie. rows and columns. A matrix can be thought of 2D array. To access any single number inside it, you need exactly two indices: matrix[row][column] (or $M_{ij}$).

In [608]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [609]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


### Tensor
In programming, Tensor is usually referring to a 3-order tensor or higher.

In [610]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [611]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


### Random Tensors
We can produce random tensors using `torch.rand`
torch.rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) → Tensor
Returns a tensor filled with random numbers from a uniform distribution on the interval 
[0,1)


In [612]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.7360, 0.4961, 0.4581],
         [0.2988, 0.7152, 0.5489]]),
 torch.float32)

In [613]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Tensors of only Zeros and Ones

In [614]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [615]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))


### Creating a range and tensors like

In [616]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)

In [617]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape

### Tensor datatypes

* Floating-Point
-These are used for real numbers with decimal points.

* Integer Types
Used for counting, indexing, or discrete values. It can be divided into signed & unsigned.

* Boolean Type
Used to store True or False values.

* Complex Type: Used to store complex numbers. It has two parts imaginary and real.

In [618]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 


In [619]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work


### Tensor Operations
We can perform the following operations in tensors:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [620]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

We can directly multiply with a value.

In [621]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [622]:
tensor

tensor([1, 2, 3])

We can alos use torch functions to perform the tensor opertaions.

In [623]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [624]:
tensor

tensor([1, 2, 3])

### Element-wise multiplication
Its also called Hadamard product or Schur product. Its the process where tensors of exactly same dimensions are multiplied. Contrary to matrix multiplication, in Element-Wise Multiplication the corresponding elements of the same dimensions are multiplied.

## Broadcasting
Since, element-wise multiplicaton requires equal sized tensors, Pytorch needs to extend tensors to make them equally sized which is called broadcasting. In short, if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (without making copies of the data).


In [625]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals: tensor([121, 144, 169])
Equals: tensor([121, 144, 169])


In [626]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


### Common errors in deep learning

```
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]], dtype=torch.float32)

 tensor_B = torch.tensor([[7, 10],
                          [8, 11], 
                          [9, 12]], dtype=torch.float32)

 torch.matmul(tensor_A, tensor_B) # (this will error)

```

In [627]:
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                          [8, 11], 
                          [9, 12]], dtype=torch.float32)
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (aggregation)

In [628]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


### Positional min/max

In [629]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Changing tensor datatype
The tensor datatype can be changed using torch functions

In [630]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)

torch.float32


### Reshaping 
Reshaping is the process of changing the shape of tensors
`torch.reshape(input, shape)` 

 `torch.Tensor.reshape()`.

In [631]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [632]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

### View
Returns a new tensor with the same data as the self tensor but of a different shape.
The returned tensor shares the same data and must have the same number of elements, but may have a different size. For a tensor to be viewed, the new view size must be compatible with its original size and stride, i.e., each new view dimension must either be a subspace of an original dimension, or only span across original dimensions.
`Tensor.view(shape)`: Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

In [633]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [634]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

### Stack
`torch.stack(tensors, dim=0)`: Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

In [635]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 

In [636]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

## [Squeeze and Unsqueeze funtions](https://www.geeksforgeeks.org/python/how-to-squeeze-and-unsqueeze-a-tensor-in-pytorch/)

### Squeezing a tensor
When we squeeze a tensor, the dimensions of size 1 are removed. The elements of the original tensor are arranged with the remaining dimensions. For example, if the input tensor is of shape: (m×1×n×1) then the output tensor after squeeze will be of shape: (m×n).

### Unsqueezing a tensor 
When we unsqueeze a tensor, a new dimension of size 1 is inserted at the specified position.  Always an unsqueeze operation increases the dimension of the output tensor. For example, if the input tensor is of shape:  (m×n) and we want to insert a new dimension at position 1 then the output tensor after unsqueeze will be of shape: (m×1×n). 

---

**To squeeze a tensor we can apply the torch.squeeze() method and to unsqueeze a tensor we use the torch.unsqueeze() method. Let's understand these methods in detail.**

In [637]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


### permute

In [638]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


### Indexing

In [639]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [640]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


### Pytorch Tensor to NumPy arrays and vice versa

In [641]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [642]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Tensors on GPU

In [643]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"

In [644]:
# Count number of devices
torch.cuda.device_count()

1

In [645]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [646]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## DISCUSSION & CONCLUSION
**PyTorch** is a Python-based deep learning library that runs on CPU by default and supports GPU acceleration using CUDA. We can set up pytorch locally by going to [Pytorh.org](https://pytorch.org/get-started/locally/). Pytorch uses Tensor as data structure. Tensor is a multidimensional array that can be processed using GPUs and support Autograd feature of Pytorch. This makes Tensor the most important data structure for machine learning. Tensor can be classified into four types on the basis of order ie.

* Scalar (0 order)
* Vector (1 order)
* Matrix (2 order)
* Tensor (n-order)

we can perform operations like addition, subtraction, multiplication etc on tensors. An important operation of equally sized Tensors is Element-wise multiplication where the elements on the same dimensions are multiplied. If the tensors are not equally sized, Pytorch extends them to make the tensors equally sized and this process is called broadcasting.

The shape of tensors can be altered using reshape functions. This can be only done if the original tensor is compatible. We can also use Tensor views to reshape the original tensor and the changes made to the view occur in the original tensor too. Views are special because we can make views that are subspaces of the original tensors. This is called tensor slicing. We can also use squeeze and unsqueeze functions to change the shape of tensors. We can use indexing just like arrays in order to access elements from the tensors.

Pytorch library supplies the users with functions that allows us to convert tensors from Pytorch to numpy arrays if needed. Hence, it can be established that Tensors are extremely important for machine learning and deep learning.